version: "3.8"

services:

  frontend:
    build: ./frontend
    container_name: frontend_cloud
    ports:
      - "8080:80"

  backend:
    build: ./backend
    container_name: backend_api
    ports:
      - "9090:80"
