name: DevOps Cloud Pipeline

on:
  push:
    branches:
      - main

jobs:

  docker-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Frontend Container
        run: |
          docker build -t frontend ./frontend

      - name: Build Backend Container
        run: |
          docker build -t backend ./backend

      - name: Pipeline Success
        run: echo "Docker build success"
